//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Size_Quantity
    {
        public int product_size_quantity_id { get; set; }
        public string product_id { get; set; }
        public string size { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
